import { rupees } from "../core/money.js";
import type { Product } from "../core/types.js";

/**
 * HamperHub's seed catalog.
 *
 * Two entries are load-bearing for the demo:
 *  - `p-coffee-arabica` is the only low-stock item, so inventory perturbation
 *    has a predictable target.
 *  - `p-choc-truffle` ships with `allergens: null` and `vegan: null`, i.e. the
 *    merchant genuinely has not supplied the data. Any integration that reads
 *    that as "allergen-free" is unsafe, which is seeded defect #4.
 */
export const SEED_CATALOG: readonly Product[] = Object.freeze([
  {
    id: "p-coffee-arabica",
    name: "Arabica Single-Origin Coffee 250g",
    category: "coffee",
    priceMinor: rupees(599),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(540),
  },
  {
    id: "p-coffee-instant",
    name: "Instant Coffee Sachets (10 pack)",
    category: "coffee",
    priceMinor: rupees(249),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(220),
  },
  {
    id: "p-coffee-beans-dark",
    name: "Dark Roast Coffee Beans 500g",
    category: "coffee",
    priceMinor: rupees(849),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(760),
  },
  {
    id: "p-tea-masala",
    name: "Masala Chai Blend 100g",
    category: "tea",
    priceMinor: rupees(229),
    priceVersion: 1,
    allergens: ["milk"],
    vegan: false,
    bundleEligible: true,
    minPriceMinor: rupees(205),
  },
  {
    id: "p-tea-green",
    name: "Himalayan Green Tea 50g",
    category: "tea",
    priceMinor: rupees(199),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(180),
  },
  {
    id: "p-choc-dark-vegan",
    name: "Vegan Dark Chocolate 70%",
    category: "chocolate",
    priceMinor: rupees(349),
    priceVersion: 1,
    allergens: ["soy"],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(315),
  },
  {
    id: "p-choc-milk",
    name: "Milk Chocolate Bar 100g",
    category: "chocolate",
    priceMinor: rupees(299),
    priceVersion: 1,
    allergens: ["milk", "soy"],
    vegan: false,
    bundleEligible: true,
    minPriceMinor: rupees(270),
  },
  {
    // Deliberately incomplete merchant data. Unknown != safe.
    id: "p-choc-truffle",
    name: "Assorted Truffle Box (imported)",
    category: "chocolate",
    priceMinor: rupees(549),
    priceVersion: 1,
    allergens: null,
    vegan: null,
    bundleEligible: true,
    minPriceMinor: rupees(495),
  },
  {
    id: "p-candle-soy",
    name: "Soy Wax Candle - Vanilla",
    category: "candle",
    priceMinor: rupees(449),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(405),
  },
  {
    id: "p-candle-beeswax",
    name: "Beeswax Candle - Honey",
    category: "candle",
    priceMinor: rupees(499),
    priceVersion: 1,
    allergens: [],
    vegan: false,
    bundleEligible: true,
    minPriceMinor: rupees(450),
  },
  {
    id: "p-mug-ceramic",
    name: "Ceramic Coffee Mug",
    category: "mug",
    priceMinor: rupees(399),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(360),
  },
  {
    id: "p-mug-steel",
    name: "Insulated Steel Travel Mug",
    category: "mug",
    priceMinor: rupees(699),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(630),
  },
  {
    id: "p-card-handmade",
    name: "Handmade Birthday Card",
    category: "card",
    priceMinor: rupees(99),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(90),
  },
  {
    id: "p-card-premium",
    name: "Premium Foil Greeting Card",
    category: "card",
    priceMinor: rupees(149),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(135),
  },
  {
    id: "p-snack-trailmix",
    name: "Roasted Trail Mix 150g",
    category: "snack",
    priceMinor: rupees(279),
    priceVersion: 1,
    allergens: ["peanut", "tree_nut"],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(250),
  },
  {
    id: "p-snack-cookies",
    name: "Butter Shortbread Cookies 200g",
    category: "snack",
    priceMinor: rupees(319),
    priceVersion: 1,
    allergens: ["wheat", "milk", "egg"],
    vegan: false,
    bundleEligible: true,
    minPriceMinor: rupees(290),
  },
  {
    id: "p-pack-giftbox",
    name: "Gift Hamper Box with Ribbon",
    category: "packaging",
    priceMinor: rupees(199),
    priceVersion: 1,
    allergens: [],
    vegan: true,
    bundleEligible: true,
    minPriceMinor: rupees(180),
  },
]);

/** Opening stock. Arabica coffee is scarce on purpose (see §12 demo). */
export const SEED_INVENTORY: Readonly<Record<string, number>> = Object.freeze({
  "p-coffee-arabica": 8,
  "p-coffee-instant": 40,
  "p-coffee-beans-dark": 15,
  "p-tea-masala": 30,
  "p-tea-green": 25,
  "p-choc-dark-vegan": 22,
  "p-choc-milk": 35,
  "p-choc-truffle": 12,
  "p-candle-soy": 18,
  "p-candle-beeswax": 14,
  "p-mug-ceramic": 20,
  "p-mug-steel": 10,
  "p-card-handmade": 50,
  "p-card-premium": 30,
  "p-snack-trailmix": 26,
  "p-snack-cookies": 24,
  "p-pack-giftbox": 60,
});
